$include conex-macros.enn
$include raylib-constants.enn

.ORG 0x0000
.SEC %PGA
	MASK
	ADRL A, @STK
	ADRM A, @STK
	WSP  A

	ADRL A, @EXVEC
	ADRM A, @EXVEC
	WXV  A

	ADRL A, @MAIN
	ADRM A, @MAIN

	JMR  A

; PGA-reachable routines
; suffixing all of these with _M
; to denote "main part" of their code
; most of these are just stubs
@DIE
	ERR
@MEMCPY
	FAR JMO @MEMCPY_M
@MEMSET
	FAR JMO @MEMSET_M
@STRLEN
	FAR JMO @STRLEN_M
@STREQ
	FAR JMO @STREQ_M
@INT_TO_DEC
	FAR JMO @INT_TO_DEC_M
@DEC_TO_INT
	FAR JMO @DEC_TO_INT_M
@INT_TO_HEX
	FAR JMO @INT_TO_HEX_M
@HEX_TO_INT
	FAR JMO @HEX_TO_INT_M
@DRAW_PX
	FAR JMO @DRAW_PX_M
@DRAW_CHAR
	FAR JMO @DRAW_CHAR_M
@PRINT_STRING
	FAR JMO @PRINT_STRING_M
@PUTCHAR_CURSOR
	FAR JMO @PUTCHAR_CURSOR_M
@CLRSCR
	FAR JMO @CLRSCR_M
@DRAW_SPRITE_16x16_GRID_ALIGNED
	FAR JMO @DRAW_SPRITE_16x16_GRID_ALIGNED_M
@DRAW_SPRITE_16x16
	FAR JMO @DRAW_SPRITE_16x16_M
@GET_TIMER
	FAR JMO @GET_TIMER_M
@DRAW_HLINE
	FAR JMO @DRAW_HLINE_M
@DRAW_VLINE
	FAR JMO @DRAW_VLINE_M
@DRAW_RECT
	FAR JMO @DRAW_RECT_M
@DRAW_RECT_FILL
	FAR JMO @DRAW_RECT_FILL_M
@POLL_DEVICE
	FAR JMO @POLL_DEVICE_M
@GET_SECTOR
	FAR JMO @GET_SECTOR_M
@LOAD_FAT_SEC0
	FAR JMO @LOAD_FAT_SEC0_M
@GET_SEC0_DATA
	FAR JMO @GET_SEC0_DATA_M
@LOAD_FAT_INTO_MEM
	FAR JMO @LOAD_FAT_INTO_MEM_M

$include pga.enn

; exceptions load an addr from
; this table by offset; XS contains
; the offset to the correct handler
; and the interrupt routine uses
; this offset to find where to jump
@EX_TABLE
.INT16 @KILL            ; 0x00
.INT16 @EX_TIMER_EVENT  ; 0x02
.INT16 @EX_KBD_EVENT    ; 0x04
.INT16 @KILL            ; 0x06

@EX_TIMER
.INT24 0x00
.INT24 0x00
@EX_TIMER_EVENT
	ADRL  A, @EX_TIMER
	ADRM  A, @EX_TIMER
	LDRS  B, A
	ADD   B, #1
	STRS  B, A+
	CEQ   B, #0
	LDRS  B, A
	ADD.P B, #1
	STRS  B, A
	RET

@EX_KBD_EVENT
	ADRL  B, @KBD_MAILBOX
	ADRM  B, @KBD_MAILBOX
	ADRH  B, @KBD_MAILBOX

	LDRW  A, B

	MOV   B, KEY_Q

	CEQ   A, B
	JMO.P @KILL

	GETL  A, A

	JLA   @PUTCHAR_CURSOR

	MOV  A, #0 ; clearing exception state
	WXS  A
	RET
@KILL
	MOV  A, #0
	JLA @POLL_DEVICE

	MOV  A, #0
	ADRL B, @FAT12_DSKBUF
	ADRM B, @FAT12_DSKBUF
	JLA  @GET_SECTOR

	ADRL B, @FAT12_DSKBUF
	ADRM B, @FAT12_DSKBUF
	MOVM A, #2
	@KILL_L1
		LDRB  C, B+
		DBGC  C
		SUB   A, #1
		JMNZO A, @KILL_L1

	JLA @GET_TIMER
	ERR
@EXVEC
	MASK
	PSHS A
	PSHS B
	RPS  A
	PSHS A

	RXS  A
	ADRL B, @EX_TABLE
	ADRM B, @EX_TABLE
	ADD  B, A
	LDRW A, B
	JLR  A

	POPS A
	WPS  A
	POPS B
	POPS A
	UNMASK
	ERET

%PGA

.ORG 0x0800
.SEC %PROG

@MAIN
	UNMASK
	MOVL A, #0xff
	MOVM A, #0xff
	MOVH A, #0xff
	ADRL B, @BUFFER
	ADRM B, @BUFFER

	JLA  @INT_TO_HEX

	ADRL A, @BUFFER
	ADRM A, @BUFFER

	JLA  @HEX_TO_INT
	
	_888_TO_565 A, 0x30, 0x00, 0x20, B
FAR JLO @CLRSCR

	ADRL A, @BUFFER ; STRING
	ADRM A, @BUFFER ; STRING
FAR JLO  @PRINT_STRING

	MOV  B, #10
	MOV  C, #10
	ADRL A, @ICON
	ADRM A, @ICON
FAR JLO  @DRAW_SPRITE_16x16_GRID_ALIGNED

	MOV  A, #0
	INV  A, A
	MOV  B, #250
	MOV  C, #125
	MOV  D, #250
	ADD  D, B
	MOV  E, #150
	JLA  @DRAW_RECT

	MOV  B, #250
	MOV  C, #170
	MOV  D, #250
	ADD  D, B
	MOV  E, #195
	JLA  @DRAW_RECT_FILL

	JLA  @LOAD_FAT_SEC0
	ADRL A, @FAT12_SECTOR_0
	ADRM A, @FAT12_SECTOR_0 
	JLA  @GET_SEC0_DATA

	ADRL A, @FAT12_FAT_AREA
	ADRM A, @FAT12_FAT_AREA
	JLA  @LOAD_FAT_INTO_MEM

	ADRL A, @FAT12_FAT_AREA
	ADRM A, @FAT12_FAT_AREA
	MOV  B, #0x01
	LSHL B, #12
	@LOOPY
		LDRB  C, A+
		DBGB  C
		SUB   B, #1
		JMNZO B, @LOOPY
	@LOOP
		WFI
		JLA  @GET_TIMER
		JMO  @LOOP
	ERR

@STRING
.ASCIZ This is 100% software-rendered,, from a string 

@BUFFER
.REP 16 0x00

%PROG
            ; <╟┐
            ;   │ grows down 
.ORG 0x1000 ;   │ from 0x1000
@STK  ; ────────┘      

.ORG 0x1000
.SEC %FAT12_AREA
; --------
; FAT-related memory

@FAT12_BYTES_PER_SECTOR
.INT16 0xffff
@FAT12_RESERVED_SECTORS
.INT16 0xffff
@FAT12_NR_FAT_TABLES
.INT8  0xff
@FAT12_ROOT_DIR_ENTRIES
.INT16 0xffff
@FAT12_SECTORS_PER_FAT
.INT16 0xffff
@FAT12_ROOT_START
.INT24 0xffffff
@FAT12_DATA_START
.INT24 0xffffff
.PAD

.ORG 0x1100
@FAT12_DSKBUF

.ORG 0x1300
@FAT12_SECTOR_0

.ORG 0x1500
@FAT12_FAT_AREA ; loading only one FAT table

.ORG 0x2700
@FAT12_ROOTDIR_AREA

.ORG 0x4300 ; 0xe0 * 0x20 (0x1c00) + 0x2700
@FAT12_END_ROOTDIR

%FAT12_AREA

.ORG 0x8000
.SEC %FONTS

; include font8.enn
$include font16.enn

@ICON
$include sprite.enn

%FONTS

.ORG 0x800000
@FRAMEBUFFER
.ORG 0x87f400
@KBD_MAILBOX
